import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import { LangContextProvider } from "@/lib/contexts/LangContext";
import { GdprContextProvider } from "@/lib/contexts/GdprContext";
import { WindowContextProvider } from "@/lib/contexts/WindowContext";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { PageTransition } from "@/components";
import GdprComponent from "@/components/gdpr";
import GlobalDonateSection from "@/app/_views/global/GlobalDonateSection";

const crimsonText = Crimson_Text({ variable: "--font-crimsonText", subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${crimsonText.variable} antialiased pt-[60px]`}>
        <WindowContextProvider>
          <GdprContextProvider>
            <LangContextProvider>
              <Navbar />
              <PageTransition>{children}</PageTransition>
              <GlobalDonateSection />
              <GdprComponent />
              <Footer />
            </LangContextProvider>
          </GdprContextProvider>
        </WindowContextProvider>
      </body>
    </html>
  );
}
