import { GET_EVENT_BY_SLUG, GET_EVENTS_LIST, GET_EVENTS_SLUGS } from "./events";
import { GET_PARTNERS_LIST } from "./partners";
import { GET_PROJECTS_SLUGS, GET_PROJECT_BY_SLUG, GET_PROJECTS_LIST } from "./projects";
import { GET_RESOURCES_BY_SLUG, GET_RESOURCES_LIST, GET_RESOURCES_SLUGS } from "./resources";
import { GET_TEAM_MEMBER_BY_SLUG, GET_TEAM_MEMBER_LIST, GET_TEAM_MEMBERS_SLUGS } from "./team";

export {
  GET_PROJECTS_SLUGS,
  GET_PROJECT_BY_SLUG,
  GET_PROJECTS_LIST,
  GET_TEAM_MEMBERS_SLUGS,
  GET_TEAM_MEMBER_BY_SLUG,
  GET_TEAM_MEMBER_LIST,
  GET_RESOURCES_SLUGS,
  GET_RESOURCES_BY_SLUG,
  GET_RESOURCES_LIST,
  GET_PARTNERS_LIST,
  GET_EVENTS_SLUGS,
  GET_EVENT_BY_SLUG,
  GET_EVENTS_LIST,
};
